#$#### Author: Ahmet Kurdoglu #####
##### Parameterized PBS Script ####
#PBS -S /bin/bash
#PBS -N pegasus_digar
#PBS -l walltime=48:00:00
#PBS -M tgenjetstream@tgen.org
#PBS -m a
#PBS -j oe
#PBS -o /${D}/oeFiles/${PBS_JOBNAME}_${PBS_JOBID}.out 
#PBS -e /${D}/oeFiles/${PBS_JOBNAME}_${PBS_JOBID}.err
 
time=`date +%d-%m-%Y-%H-%M`
beginTime=`date +%s`
machine=`hostname`
echo "### NODE: $machine"
echo "### REF: ${REF}"
echo "### DIGARDIR: ${DIGARDIR}"
echo "### RUNDIR: ${RUNDIR}"
echo "### BAM: ${BAM}"
echo "### FASTQ1: ${FASTQ1}"
echo "### FASTQ2: ${FASTQ2}"
echo "### ANN: ${ANN}"
echo "### GENENAME: ${GENENAME}"
echo "### GTF: ${GTF}"
echo "### SAMTOOLSPATH: ${SAMTOOLSPATH}"
echo "### BWAPATH: ${BWAPATH}"
echo "### DIGARPATH: ${DIGARPATH}"
echo "### NXT1 is: ${NXT1}"
echo "### LISTOFGENES is: ${LISTOFGENES}"

echo "TIME:$time starting digar on ${DIGARDIR}"
cd ${DIGARDIR}

perf stat ${DIGARPATH}/digarSteps.current.pl \
	--dir ${DIGARDIR} \
	--left ${FASTQ1} \
	--right ${FASTQ2} \
	--input ${GENENAME} \
	--bam ${BAM} \
	--genome ${REF} \
	--ann ${ANN} \
	--samPath ${SAMTOOLSPATH} \
	--trinity ${TRINITYPATH} \
	--path ${DIGARPATH} \
	--mem ${BWAPATH} 2> ${DIGARDIR}/${SAMNAME}.digar.${GENENAME}.perfOut > ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarOut 2>&1
if [ $? -eq 0 ] ; then
	#finished successfully
	mv ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarOut ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarPass
	echo "${GENENAME}:PASS" >> ${DIGARDIR}/geneDone.txt
	genesDone=`cat ${DIGARDIR}/geneDone.txt | wc -l`
	numGenesInList=`cat $LISTOFGENES | wc -l`
	echo "genesDone = $genesDone"
	echo "numGenesInList = $numGenesInList"
	if [ $genesDone -eq $numGenesInList ] ; then
		touch ${DIGARDIR}.digarPass
		touch ${RUNDIR}/${NXT1}
	fi
else
	mv ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarOut ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarFailDIGAR
	echo "${GENENAME}:FAIL" >> ${DIGARDIR}/geneDone.txt
	genesDone=`cat ${DIGARDIR}/geneDone.txt | wc -l`
        numGenesInList=`cat $LISTOFGENES | wc -l`
	echo "genesDone = $genesDone"
        echo "numGenesInList = $numGenesInList"
	if [ $genesDone -eq $numGenesInList ] ; then
                touch ${DIGARDIR}.digarPass
                touch ${RUNDIR}/${NXT1}
        fi
fi

rm -f ${DIGARDIR}/${SAMNAME}.${GENENAME}.digarInQueue
endTime=`date +%s`
elapsed=$(( $endTime - $beginTime ))
(( hours=$elapsed/3600 ))
(( mins=$elapsed%3600/60 ))
echo "RUNTIME:DIGAR.${GENENAME}:$hours:$mins" > ${DIGARDIR}/${SAMNAME}.${GENENAME}.digar.totalTime

time=`date +%d-%m-%Y-%H-%M`
echo "TIME:$time finished digar on ${DIGARDIR}.${GENENAME}"
