##### Author: Ahmet Kurdoglu #####
##### Parameterized PBS Script ####
#PBS -S /bin/bash
#PBS -N pegasus_soapFuse
#PBS -l walltime=96:00:00
#PBS -M tgenjetstream@tgen.org
#PBS -m a
#PBS -j oe
#PBS -o /${D}/oeFiles/${PBS_JOBNAME}_${PBS_JOBID}.out 
#PBS -e /${D}/oeFiles/${PBS_JOBNAME}_${PBS_JOBID}.err

echo "### Variables coming in:"
echo "### SAMPLE=${SAMPLE}"
echo "### SPCONFIG=${SPCONFIG}"
echo "### REF=${REF}"
echo "### FAI=${FAI}"
echo "### FASTQ1=${FASTQ1}"
echo "### FASTQ2=${FASTQ2}"
echo "### DIR=${DIR}"
echo "### SOAPFUSEPATH: ${SOAPFUSEPATH}"
echo "### SAMTOOLSPATH: ${SAMTOOLSPATH}"

time=`date +%d-%m-%Y-%H-%M`
beginTime=`date +%s`

echo "TIME:$time starting soap fuse on ${FASTQ1}"
base=`basename ${FASTQ1}`
anotherName=${base/.R1.fastq.gz}

perf stat ${SOAPFUSEPATH}/SOAPfuse-RUN.pl \
	-c ${SPCONFIG} \
	-fd ${DIR} \
	-l ${SLFILE} \
	-o ${DIR} \
	-fs 1 \
	-es 9 \
	-tp ${SAMPLE} > ${DIR}.soapFuseOut 2> ${DIR}.soapFuse.perfOut
if [ $? -eq 0 ] ; then
	echo "### Success."
	#echo "### Renaming..."
	#mv ${DIR}/accepted_hits.bam ${DIR}/$anotherName.accepted_hits.bam
	#mv ${DIR}/unmapped.bam ${DIR}/$anotherName.unmapped.bam
	#mv ${DIR}/junctions.bed ${DIR}/$anotherName.junctions.bed
	#mv ${DIR}/insertions.bed ${DIR}/$anotherName.insertions.bed
	#mv ${DIR}/deletions.bed ${DIR}/$anotherName.deletions.bed
	#mv ${DIR}/fusions.out ${DIR}/$anotherName.fusions.out
	#echo "### Renaming done"
	#echo "Now making bam index and flagstat for ${DIR}/accepted_hits.bam"
	#${SAMTOOLSPATH}/samtools index ${DIR}/$anotherName.accepted_hits.bam
	#${SAMTOOLSPATH}/samtools flagstat ${DIR}/$anotherName.accepted_hits.bam > ${DIR}/$anotherName.accepted_hits.bam.samStats
	#echo "bam indexing and flagstat finished"

	mv ${DIR}.soapFuseOut ${DIR}.soapFusePass	
	touch ${RUNDIR}/${NXT1}
else
	mv ${DIR}.soapFuseOut ${DIR}.soapFuseFail
fi
rm -f ${DIR}.soapFuseInQueue
endTime=`date +%s`
elapsed=$(( $endTime - $beginTime ))
(( hours=$elapsed/3600 ))
(( mins=$elapsed%3600/60 ))
echo "RUNTIME:SOAPFUSE:$hours:$mins" > ${DIR}/$anotherName.accepted_hits.bam.thFusion.totalTime

time=`date +%d-%m-%Y-%H-%M`
echo "TIME:$time soap fuse finished"
